<a href="https://colab.research.google.com/github/MasterAKhan/ML-models/blob/main/torch_autograde_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

Trying Autograde

In [4]:
x=torch.tensor(3.0,requires_grad=True)

In [5]:
y=x**2

In [7]:
x

tensor(3., requires_grad=True)

In [8]:
y

tensor(9., grad_fn=<PowBackward0>)

In [9]:
y.backward()

In [11]:
x.grad

tensor(6.)

Another example

In [28]:
x=torch.tensor(2.0,requires_grad=True)

In [29]:
y=torch.sin(x**3)

In [30]:
x

tensor(2., requires_grad=True)

In [31]:
y

tensor(0.9894, grad_fn=<SinBackward0>)

In [32]:
y.backward()

In [33]:
x.grad

tensor(-1.7460)

In [34]:
print(3*(x**2)*(torch.cos(x**3)))

tensor(-1.7460, grad_fn=<MulBackward0>)


so we can add nersted function and still find their auto grade

Now, try to find double diffirinatation

In [48]:
x=torch.tensor(2.0,requires_grad=True)

In [49]:
y=x**4

In [50]:
x

tensor(2., requires_grad=True)

In [51]:
y

tensor(16., grad_fn=<PowBackward0>)

In [52]:
ydash=torch.autograd.grad(y,x, create_graph=True)[0]

In [53]:
print(ydash)

tensor(32., grad_fn=<MulBackward0>)


In [54]:
ydashdash=torch.autograd.grad(ydash,x)[0]

In [55]:
print(ydashdash)

tensor(48.)


In [56]:
print(4*3*2**2)

48


now try auto grade on matrix

In [57]:
x=torch.rand(3,3,requires_grad=True)

In [58]:
y=torch.matmul(x,x.T)

In [59]:
x

tensor([[0.3061, 0.3930, 0.5236],
        [0.5304, 0.7959, 0.0424],
        [0.3559, 0.0135, 0.5710]], requires_grad=True)

In [60]:
y

tensor([[0.5224, 0.4974, 0.4133],
        [0.4974, 0.9165, 0.2238],
        [0.4133, 0.2238, 0.4529]], grad_fn=<MmBackward0>)

In [62]:
# y is a matrix, so we need a scalar loss to call backward() implicitly.
# We can sum the elements of y to get a scalar loss.
scalar_loss = torch.sum(y)

# Now call backward() on the scalar loss
scalar_loss.backward()

# The gradients are now accumulated in x.grad
print(x.grad)

tensor([[2.3850, 2.4049, 2.2740],
        [2.3850, 2.4049, 2.2740],
        [2.3850, 2.4049, 2.2740]])


Last cell i used gemini as i tried to find gradient of non scaler function thats not allowed

Now try to build simple neuron and try to find derivative of loss with respect to weight and baise

In [80]:
x=torch.linspace(0,100,17)

In [81]:
x

tensor([  0.0000,   6.2500,  12.5000,  18.7500,  25.0000,  31.2500,  37.5000,
         43.7500,  50.0000,  56.2500,  62.5000,  68.7500,  75.0000,  81.2500,
         87.5000,  93.7500, 100.0000])

In [82]:
w=torch.linspace(0,10,17,requires_grad=True)

In [83]:
b=torch.tensor(3.1, requires_grad=True)

In [84]:
w

tensor([ 0.0000,  0.6250,  1.2500,  1.8750,  2.5000,  3.1250,  3.7500,  4.3750,
         5.0000,  5.6250,  6.2500,  6.8750,  7.5000,  8.1250,  8.7500,  9.3750,
        10.0000], requires_grad=True)

In [85]:
b

tensor(3.1000, requires_grad=True)

In [86]:
y=torch.dot(w,x)+b

In [87]:
y

tensor(5846.8501, grad_fn=<AddBackward0>)

In [88]:
y.backward()

In [89]:
w.grad

tensor([  0.0000,   6.2500,  12.5000,  18.7500,  25.0000,  31.2500,  37.5000,
         43.7500,  50.0000,  56.2500,  62.5000,  68.7500,  75.0000,  81.2500,
         87.5000,  93.7500, 100.0000])

In [90]:
b.grad

tensor(1.)