<a href="https://colab.research.google.com/github/MasterAKhan/ML-models/blob/main/torch_tenser_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
    print("CUDA is available")
else:
    print("CUDA is not available")

CUDA is not available


In [5]:
a=torch.empty(3,5)

In [6]:
type(a)

torch.Tensor

In [7]:
 torch.zeros(5,9)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
torch.ones(100,200)

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [9]:
torch.rand(8,9,4)

tensor([[[1.9615e-01, 1.0208e-01, 9.5345e-02, 9.9132e-01],
         [3.3002e-02, 5.2167e-01, 9.9922e-01, 7.9154e-01],
         [5.9866e-01, 2.1566e-01, 4.0413e-02, 5.0585e-01],
         [8.7756e-01, 4.3546e-01, 8.6878e-01, 2.0428e-01],
         [2.1206e-01, 4.4415e-01, 3.7741e-01, 7.7336e-01],
         [5.0077e-01, 8.3942e-02, 6.3022e-01, 5.4324e-01],
         [6.6341e-01, 5.0391e-02, 9.1839e-01, 4.1334e-01],
         [5.2096e-01, 8.4394e-01, 6.5116e-02, 9.1340e-02],
         [6.8500e-01, 5.5090e-02, 2.5112e-01, 5.0590e-01]],

        [[3.9120e-01, 6.4602e-01, 6.7059e-01, 5.4146e-01],
         [7.4363e-01, 9.1422e-04, 3.1371e-01, 4.3213e-01],
         [8.7541e-03, 1.6701e-01, 6.7236e-01, 4.5120e-01],
         [8.6809e-03, 7.7605e-01, 7.3057e-01, 1.3799e-01],
         [6.1158e-01, 2.5753e-01, 4.7177e-01, 9.5639e-01],
         [4.8594e-01, 5.9136e-01, 5.8741e-01, 5.4408e-01],
         [8.3374e-01, 9.5357e-02, 8.4530e-02, 6.8757e-01],
         [6.2029e-01, 2.2628e-01, 1.4754e-01, 4.1628e-

In [11]:
torch.manual_seed(55)
torch.rand(1,2,3,4,5)

tensor([[[[[0.8357, 0.9378, 0.7439, 0.5674, 0.8682],
           [0.4765, 0.0858, 0.7740, 0.9677, 0.1874],
           [0.0993, 0.0611, 0.8334, 0.7835, 0.5216],
           [0.8003, 0.7370, 0.3124, 0.3930, 0.3130]],

          [[0.1657, 0.8543, 0.5834, 0.5361, 0.3396],
           [0.2773, 0.2879, 0.1420, 0.5896, 0.3333],
           [0.0379, 0.8650, 0.3166, 0.5783, 0.1667],
           [0.5595, 0.1936, 0.5655, 0.9738, 0.8782]],

          [[0.6017, 0.1039, 0.7762, 0.5858, 0.2360],
           [0.1285, 0.8696, 0.3406, 0.9810, 0.7909],
           [0.9879, 0.5625, 0.4525, 0.1225, 0.0546],
           [0.4135, 0.4467, 0.8914, 0.3922, 0.6505]]],


         [[[0.1817, 0.2108, 0.5676, 0.7632, 0.7862],
           [0.6145, 0.0329, 0.8410, 0.7910, 0.6366],
           [0.6257, 0.8640, 0.2799, 0.3217, 0.8696],
           [0.4442, 0.7356, 0.4944, 0.9403, 0.5335]],

          [[0.8647, 0.5889, 0.0201, 0.2061, 0.9783],
           [0.7178, 0.1711, 0.9404, 0.3730, 0.9006],
           [0.4528, 0.2851, 0.3506, 

In [13]:
torch.tensor([[1, 2], [3, 4]])

tensor([[1, 2],
        [3, 4]])

In [14]:
torch.arange(3,10)

tensor([3, 4, 5, 6, 7, 8, 9])

In [15]:
torch.arange(4,4,5,3)

TypeError: arange() received an invalid combination of arguments - got (int, int, int, int), but expected one of:
 * (Number end, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (Number start, Number end, *, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (Number start, Number end, Number step = 1, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)


In [16]:
torch.arange(9,8,3)

RuntimeError: upper bound and larger bound inconsistent with step sign

In [17]:
torch.arange(100,200,4)

tensor([100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152,
        156, 160, 164, 168, 172, 176, 180, 184, 188, 192, 196])

In [18]:
torch.linspace(1,10,10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
torch.linspace(3,92,493)

tensor([ 3.0000,  3.1809,  3.3618,  3.5427,  3.7236,  3.9045,  4.0854,  4.2663,
         4.4472,  4.6280,  4.8089,  4.9898,  5.1707,  5.3516,  5.5325,  5.7134,
         5.8943,  6.0752,  6.2561,  6.4370,  6.6179,  6.7988,  6.9797,  7.1606,
         7.3415,  7.5224,  7.7033,  7.8841,  8.0650,  8.2459,  8.4268,  8.6077,
         8.7886,  8.9695,  9.1504,  9.3313,  9.5122,  9.6931,  9.8740, 10.0549,
        10.2358, 10.4167, 10.5976, 10.7785, 10.9593, 11.1402, 11.3211, 11.5020,
        11.6829, 11.8638, 12.0447, 12.2256, 12.4065, 12.5874, 12.7683, 12.9492,
        13.1301, 13.3110, 13.4919, 13.6728, 13.8537, 14.0346, 14.2154, 14.3963,
        14.5772, 14.7581, 14.9390, 15.1199, 15.3008, 15.4817, 15.6626, 15.8435,
        16.0244, 16.2053, 16.3862, 16.5671, 16.7480, 16.9289, 17.1098, 17.2907,
        17.4715, 17.6524, 17.8333, 18.0142, 18.1951, 18.3760, 18.5569, 18.7378,
        18.9187, 19.0996, 19.2805, 19.4614, 19.6423, 19.8232, 20.0041, 20.1850,
        20.3659, 20.5467, 20.7276, 20.90

In [20]:
torch.eye(99)

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [21]:
torch.full((8,5,2),9)

tensor([[[9, 9],
         [9, 9],
         [9, 9],
         [9, 9],
         [9, 9]],

        [[9, 9],
         [9, 9],
         [9, 9],
         [9, 9],
         [9, 9]],

        [[9, 9],
         [9, 9],
         [9, 9],
         [9, 9],
         [9, 9]],

        [[9, 9],
         [9, 9],
         [9, 9],
         [9, 9],
         [9, 9]],

        [[9, 9],
         [9, 9],
         [9, 9],
         [9, 9],
         [9, 9]],

        [[9, 9],
         [9, 9],
         [9, 9],
         [9, 9],
         [9, 9]],

        [[9, 9],
         [9, 9],
         [9, 9],
         [9, 9],
         [9, 9]],

        [[9, 9],
         [9, 9],
         [9, 9],
         [9, 9],
         [9, 9]]])

In [23]:
torch.ones(3,4,5,6)

tensor([[[[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1

In [25]:
s=torch.tensor([[1,2,3],[3,4,5]])

In [27]:
s.shape

torch.Size([2, 3])

In [28]:
torch.empty_like(s)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [29]:
torch.zeros_like(s)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [30]:
s.dtype

torch.int64

In [34]:
torch.tensor([[1.0,2.0],[3.4,5.9]],dtype=torch.int32)

tensor([[1, 2],
        [3, 5]], dtype=torch.int32)

In [35]:
x=torch.rand(3,3,3)

In [36]:
x

tensor([[[0.7614, 0.4717, 0.0498],
         [0.6186, 0.3506, 0.0336],
         [0.0145, 0.1791, 0.1090]],

        [[0.6985, 0.8686, 0.9210],
         [0.5163, 0.6263, 0.4645],
         [0.9725, 0.2080, 0.1035]],

        [[0.0810, 0.6824, 0.5409],
         [0.0772, 0.1820, 0.9708],
         [0.1649, 0.1187, 0.1201]]])

In [37]:
x+2

tensor([[[2.7614, 2.4717, 2.0498],
         [2.6186, 2.3506, 2.0336],
         [2.0145, 2.1791, 2.1090]],

        [[2.6985, 2.8686, 2.9210],
         [2.5163, 2.6263, 2.4645],
         [2.9725, 2.2080, 2.1035]],

        [[2.0810, 2.6824, 2.5409],
         [2.0772, 2.1820, 2.9708],
         [2.1649, 2.1187, 2.1201]]])

In [38]:
x-2

tensor([[[-1.2386, -1.5283, -1.9502],
         [-1.3814, -1.6494, -1.9664],
         [-1.9855, -1.8209, -1.8910]],

        [[-1.3015, -1.1314, -1.0790],
         [-1.4837, -1.3737, -1.5355],
         [-1.0275, -1.7920, -1.8965]],

        [[-1.9190, -1.3176, -1.4591],
         [-1.9228, -1.8180, -1.0292],
         [-1.8351, -1.8813, -1.8799]]])

In [39]:
x*2

tensor([[[1.5228, 0.9433, 0.0996],
         [1.2371, 0.7011, 0.0671],
         [0.0291, 0.3581, 0.2179]],

        [[1.3969, 1.7372, 1.8420],
         [1.0326, 1.2525, 0.9289],
         [1.9450, 0.4160, 0.2070]],

        [[0.1620, 1.3648, 1.0817],
         [0.1543, 0.3640, 1.9417],
         [0.3298, 0.2374, 0.2402]]])

In [40]:
x

tensor([[[0.7614, 0.4717, 0.0498],
         [0.6186, 0.3506, 0.0336],
         [0.0145, 0.1791, 0.1090]],

        [[0.6985, 0.8686, 0.9210],
         [0.5163, 0.6263, 0.4645],
         [0.9725, 0.2080, 0.1035]],

        [[0.0810, 0.6824, 0.5409],
         [0.0772, 0.1820, 0.9708],
         [0.1649, 0.1187, 0.1201]]])

In [41]:
x*10

tensor([[[7.6142, 4.7167, 0.4981],
         [6.1856, 3.5057, 0.3356],
         [0.1454, 1.7907, 1.0897]],

        [[6.9847, 8.6860, 9.2102],
         [5.1632, 6.2626, 4.6447],
         [9.7248, 2.0802, 1.0350]],

        [[0.8100, 6.8239, 5.4086],
         [0.7717, 1.8201, 9.7083],
         [1.6492, 1.1868, 1.2012]]])

In [42]:
x/2

tensor([[[0.3807, 0.2358, 0.0249],
         [0.3093, 0.1753, 0.0168],
         [0.0073, 0.0895, 0.0545]],

        [[0.3492, 0.4343, 0.4605],
         [0.2582, 0.3131, 0.2322],
         [0.4862, 0.1040, 0.0517]],

        [[0.0405, 0.3412, 0.2704],
         [0.0386, 0.0910, 0.4854],
         [0.0825, 0.0593, 0.0601]]])

In [44]:
x**2

tensor([[[5.7975e-01, 2.2247e-01, 2.4810e-03],
         [3.8262e-01, 1.2290e-01, 1.1264e-03],
         [2.1132e-04, 3.2067e-02, 1.1874e-02]],

        [[4.8786e-01, 7.5446e-01, 8.4828e-01],
         [2.6659e-01, 3.9220e-01, 2.1573e-01],
         [9.4572e-01, 4.3271e-02, 1.0712e-02]],

        [[6.5616e-03, 4.6565e-01, 2.9253e-01],
         [5.9559e-03, 3.3129e-02, 9.4250e-01],
         [2.7198e-02, 1.4084e-02, 1.4429e-02]]])

In [46]:
c=torch.arange(-30,20,2)

In [47]:
c

tensor([-30, -28, -26, -24, -22, -20, -18, -16, -14, -12, -10,  -8,  -6,  -4,
         -2,   0,   2,   4,   6,   8,  10,  12,  14,  16,  18])

In [48]:
torch.abs(c)

tensor([30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0,  2,  4,
         6,  8, 10, 12, 14, 16, 18])

In [49]:
torch.neg(c)

tensor([ 30,  28,  26,  24,  22,  20,  18,  16,  14,  12,  10,   8,   6,   4,
          2,   0,  -2,  -4,  -6,  -8, -10, -12, -14, -16, -18])

In [50]:
a=torch.linspace(2,33,44)

In [51]:
a

tensor([ 2.0000,  2.7209,  3.4419,  4.1628,  4.8837,  5.6047,  6.3256,  7.0465,
         7.7674,  8.4884,  9.2093,  9.9302, 10.6512, 11.3721, 12.0930, 12.8140,
        13.5349, 14.2558, 14.9767, 15.6977, 16.4186, 17.1395, 17.8605, 18.5814,
        19.3023, 20.0233, 20.7442, 21.4651, 22.1860, 22.9070, 23.6279, 24.3488,
        25.0698, 25.7907, 26.5116, 27.2326, 27.9535, 28.6744, 29.3953, 30.1163,
        30.8372, 31.5581, 32.2791, 33.0000])

In [52]:
torch.round(a)

tensor([ 2.,  3.,  3.,  4.,  5.,  6.,  6.,  7.,  8.,  8.,  9., 10., 11., 11.,
        12., 13., 14., 14., 15., 16., 16., 17., 18., 19., 19., 20., 21., 21.,
        22., 23., 24., 24., 25., 26., 27., 27., 28., 29., 29., 30., 31., 32.,
        32., 33.])

In [53]:
torch.ceil(a)

tensor([ 2.,  3.,  4.,  5.,  5.,  6.,  7.,  8.,  8.,  9., 10., 10., 11., 12.,
        13., 13., 14., 15., 15., 16., 17., 18., 18., 19., 20., 21., 21., 22.,
        23., 23., 24., 25., 26., 26., 27., 28., 28., 29., 30., 31., 31., 32.,
        33., 33.])

In [54]:
torch.floor(a)

tensor([ 2.,  2.,  3.,  4.,  4.,  5.,  6.,  7.,  7.,  8.,  9.,  9., 10., 11.,
        12., 12., 13., 14., 14., 15., 16., 17., 17., 18., 19., 20., 20., 21.,
        22., 22., 23., 24., 25., 25., 26., 27., 27., 28., 29., 30., 30., 31.,
        32., 33.])

In [55]:
torch.clamp(a,min=10,max=20)

tensor([10.0000, 10.0000, 10.0000, 10.0000, 10.0000, 10.0000, 10.0000, 10.0000,
        10.0000, 10.0000, 10.0000, 10.0000, 10.6512, 11.3721, 12.0930, 12.8140,
        13.5349, 14.2558, 14.9767, 15.6977, 16.4186, 17.1395, 17.8605, 18.5814,
        19.3023, 20.0000, 20.0000, 20.0000, 20.0000, 20.0000, 20.0000, 20.0000,
        20.0000, 20.0000, 20.0000, 20.0000, 20.0000, 20.0000, 20.0000, 20.0000,
        20.0000, 20.0000, 20.0000, 20.0000])

In [56]:
torch.sum(a)

tensor(770.)

In [57]:
torch.sum(a,dim=0)

tensor(770.)

In [62]:
a=torch.rand(2,3,4,5)
a

tensor([[[[0.3509, 0.0982, 0.7270, 0.3027, 0.2607],
          [0.1715, 0.8967, 0.2708, 0.5139, 0.7292],
          [0.2031, 0.3983, 0.2588, 0.2436, 0.2534],
          [0.3825, 0.0097, 0.0719, 0.5607, 0.0022]],

         [[0.5394, 0.3557, 0.0650, 0.7907, 0.9185],
          [0.7578, 0.2405, 0.0568, 0.9935, 0.0372],
          [0.6922, 0.6903, 0.8722, 0.7505, 0.2787],
          [0.2912, 0.9838, 0.1701, 0.5601, 0.8533]],

         [[0.8015, 0.9324, 0.7178, 0.7172, 0.1984],
          [0.1798, 0.3967, 0.2605, 0.5943, 0.3253],
          [0.8236, 0.9487, 0.4531, 0.4854, 0.8004],
          [0.7826, 0.4564, 0.0650, 0.7478, 0.1723]]],


        [[[0.7305, 0.7339, 0.3126, 0.2130, 0.4324],
          [0.8849, 0.7208, 0.2051, 0.7015, 0.9078],
          [0.9973, 0.4386, 0.9188, 0.9231, 0.0811],
          [0.1198, 0.3288, 0.3854, 0.2074, 0.6181]],

         [[0.2721, 0.5268, 0.2223, 0.4263, 0.3600],
          [0.8958, 0.0888, 0.6263, 0.4794, 0.3893],
          [0.9220, 0.5418, 0.9611, 0.3415, 0.2530],
  

In [66]:
torch.sum(a,dim=3)

tensor([[[1.7395, 2.5821, 1.3572, 1.0269],
         [2.6693, 2.0857, 3.2839, 2.8586],
         [3.3672, 1.7565, 3.5111, 2.2241]],

        [[2.4223, 3.4200, 3.3589, 1.6595],
         [1.8075, 2.4796, 3.0195, 2.3433],
         [2.3929, 1.4574, 3.3368, 1.9340]]])

In [67]:
torch.mean(a)

tensor(0.4841)

In [68]:
 torch.median(a)

tensor(0.4562)

In [69]:
torch.min(a)

tensor(0.0022)

In [70]:
torch.max(a)

tensor(0.9973)

In [71]:
torch.prod(a)

tensor(0.)

In [72]:
torch.std(a)

tensor(0.2868)

In [73]:
torch.var(a)

tensor(0.0823)

In [75]:
torch.max(a)


tensor(0.9973)

In [78]:
torch.argmax(a)

tensor(70)

In [79]:
torch.argmin(a)

tensor(19)

In [80]:
a=torch.rand(2,4)
b=torch.rand(4,6)

In [81]:
torch.matmul(a,b)

tensor([[0.9327, 0.8561, 0.5295, 0.9519, 0.4479, 0.4462],
        [1.7574, 1.4950, 1.4220, 0.4435, 0.5694, 1.3261]])

In [82]:
torch.matmul(torch.rand(2,4),torch.rand(4,6))

tensor([[1.1301, 1.1772, 0.4282, 0.7475, 1.1454, 0.7672],
        [1.2505, 0.8690, 1.0775, 0.9423, 1.0205, 0.9953]])

In [83]:
torch.dot(torch.rand(4),torch.rand(4))

tensor(1.1680)

In [85]:
a

tensor([[0.2193, 0.2074, 0.8977, 0.3211],
        [0.6361, 0.7466, 0.0370, 0.9360]])

In [87]:
torch.transpose(a, 0, 1)

tensor([[0.2193, 0.6361],
        [0.2074, 0.7466],
        [0.8977, 0.0370],
        [0.3211, 0.9360]])

In [91]:
a=torch.rand(7,7)
a

tensor([[0.4927, 0.8721, 0.3141, 0.5521, 0.8543, 0.0275, 0.9464],
        [0.9548, 0.6106, 0.4742, 0.5936, 0.6185, 0.7981, 0.0581],
        [0.7305, 0.8180, 0.7415, 0.6607, 0.7433, 0.1092, 0.2394],
        [0.7475, 0.3925, 0.9360, 0.3284, 0.9964, 0.5804, 0.3412],
        [0.2051, 0.2392, 0.2529, 0.5890, 0.1666, 0.0497, 0.9420],
        [0.6509, 0.1107, 0.1052, 0.1031, 0.4124, 0.1145, 0.6214],
        [0.0446, 0.0754, 0.3929, 0.6651, 0.5798, 0.0111, 0.8041]])

In [92]:
torch.det(a)

tensor(0.0717)

In [96]:
a=torch.rand(25,25)*10

In [97]:
a

tensor([[1.3577, 3.6311, 6.7705, 6.1169, 8.7142, 7.5921, 4.1551, 8.9718, 9.2723,
         7.6291, 3.8155, 1.9676, 3.6209, 8.2452, 3.1352, 1.2790, 4.8832, 8.0913,
         2.6578, 6.9338, 8.4332, 4.0321, 8.9683, 9.5913, 5.7509],
        [4.1142, 7.7750, 2.1224, 6.5394, 8.1543, 3.8201, 8.4755, 7.1295, 9.4519,
         3.1160, 8.7928, 3.5370, 9.6017, 7.6200, 2.9053, 2.1415, 9.5509, 5.3539,
         8.1433, 1.2829, 2.5521, 6.1214, 0.7329, 5.4080, 8.9745],
        [7.1751, 6.8499, 1.1551, 0.1039, 6.1176, 6.3886, 7.4506, 1.9410, 0.6111,
         2.6706, 9.7527, 4.1591, 0.1683, 3.2357, 5.1731, 6.6245, 2.5212, 2.7152,
         2.5214, 6.5448, 4.2963, 9.0790, 3.2796, 3.4917, 2.0514],
        [0.9844, 4.1298, 3.5790, 7.3979, 8.1865, 8.6870, 3.6926, 3.8140, 1.4489,
         7.3848, 0.6666, 8.0612, 6.8203, 3.4715, 4.5602, 4.6047, 2.0010, 3.0495,
         2.2635, 9.9199, 5.2629, 6.9849, 5.6733, 4.2032, 7.8046],
        [0.3356, 8.3926, 8.0065, 6.5007, 8.8335, 4.7945, 8.7609, 9.3530, 6.4620,
       

In [98]:
torch.det(a)

tensor(-1.7927e+23)

In [101]:
b=a.clone()

In [102]:
b

tensor([[1.3577, 3.6311, 6.7705, 6.1169, 8.7142, 7.5921, 4.1551, 8.9718, 9.2723,
         7.6291, 3.8155, 1.9676, 3.6209, 8.2452, 3.1352, 1.2790, 4.8832, 8.0913,
         2.6578, 6.9338, 8.4332, 4.0321, 8.9683, 9.5913, 5.7509],
        [4.1142, 7.7750, 2.1224, 6.5394, 8.1543, 3.8201, 8.4755, 7.1295, 9.4519,
         3.1160, 8.7928, 3.5370, 9.6017, 7.6200, 2.9053, 2.1415, 9.5509, 5.3539,
         8.1433, 1.2829, 2.5521, 6.1214, 0.7329, 5.4080, 8.9745],
        [7.1751, 6.8499, 1.1551, 0.1039, 6.1176, 6.3886, 7.4506, 1.9410, 0.6111,
         2.6706, 9.7527, 4.1591, 0.1683, 3.2357, 5.1731, 6.6245, 2.5212, 2.7152,
         2.5214, 6.5448, 4.2963, 9.0790, 3.2796, 3.4917, 2.0514],
        [0.9844, 4.1298, 3.5790, 7.3979, 8.1865, 8.6870, 3.6926, 3.8140, 1.4489,
         7.3848, 0.6666, 8.0612, 6.8203, 3.4715, 4.5602, 4.6047, 2.0010, 3.0495,
         2.2635, 9.9199, 5.2629, 6.9849, 5.6733, 4.2032, 7.8046],
        [0.3356, 8.3926, 8.0065, 6.5007, 8.8335, 4.7945, 8.7609, 9.3530, 6.4620,
       

In [103]:
a[0][0]=0

In [104]:
a

tensor([[0.0000, 3.6311, 6.7705, 6.1169, 8.7142, 7.5921, 4.1551, 8.9718, 9.2723,
         7.6291, 3.8155, 1.9676, 3.6209, 8.2452, 3.1352, 1.2790, 4.8832, 8.0913,
         2.6578, 6.9338, 8.4332, 4.0321, 8.9683, 9.5913, 5.7509],
        [4.1142, 7.7750, 2.1224, 6.5394, 8.1543, 3.8201, 8.4755, 7.1295, 9.4519,
         3.1160, 8.7928, 3.5370, 9.6017, 7.6200, 2.9053, 2.1415, 9.5509, 5.3539,
         8.1433, 1.2829, 2.5521, 6.1214, 0.7329, 5.4080, 8.9745],
        [7.1751, 6.8499, 1.1551, 0.1039, 6.1176, 6.3886, 7.4506, 1.9410, 0.6111,
         2.6706, 9.7527, 4.1591, 0.1683, 3.2357, 5.1731, 6.6245, 2.5212, 2.7152,
         2.5214, 6.5448, 4.2963, 9.0790, 3.2796, 3.4917, 2.0514],
        [0.9844, 4.1298, 3.5790, 7.3979, 8.1865, 8.6870, 3.6926, 3.8140, 1.4489,
         7.3848, 0.6666, 8.0612, 6.8203, 3.4715, 4.5602, 4.6047, 2.0010, 3.0495,
         2.2635, 9.9199, 5.2629, 6.9849, 5.6733, 4.2032, 7.8046],
        [0.3356, 8.3926, 8.0065, 6.5007, 8.8335, 4.7945, 8.7609, 9.3530, 6.4620,
       

In [105]:
b

tensor([[1.3577, 3.6311, 6.7705, 6.1169, 8.7142, 7.5921, 4.1551, 8.9718, 9.2723,
         7.6291, 3.8155, 1.9676, 3.6209, 8.2452, 3.1352, 1.2790, 4.8832, 8.0913,
         2.6578, 6.9338, 8.4332, 4.0321, 8.9683, 9.5913, 5.7509],
        [4.1142, 7.7750, 2.1224, 6.5394, 8.1543, 3.8201, 8.4755, 7.1295, 9.4519,
         3.1160, 8.7928, 3.5370, 9.6017, 7.6200, 2.9053, 2.1415, 9.5509, 5.3539,
         8.1433, 1.2829, 2.5521, 6.1214, 0.7329, 5.4080, 8.9745],
        [7.1751, 6.8499, 1.1551, 0.1039, 6.1176, 6.3886, 7.4506, 1.9410, 0.6111,
         2.6706, 9.7527, 4.1591, 0.1683, 3.2357, 5.1731, 6.6245, 2.5212, 2.7152,
         2.5214, 6.5448, 4.2963, 9.0790, 3.2796, 3.4917, 2.0514],
        [0.9844, 4.1298, 3.5790, 7.3979, 8.1865, 8.6870, 3.6926, 3.8140, 1.4489,
         7.3848, 0.6666, 8.0612, 6.8203, 3.4715, 4.5602, 4.6047, 2.0010, 3.0495,
         2.2635, 9.9199, 5.2629, 6.9849, 5.6733, 4.2032, 7.8046],
        [0.3356, 8.3926, 8.0065, 6.5007, 8.8335, 4.7945, 8.7609, 9.3530, 6.4620,
       

In [106]:
b[0][0]-a[0][0]

tensor(1.3577)

In [107]:
id(a)

134423795778864

In [108]:
id(b)

134423795519024

In [109]:
id(a)-id(b)

259840

In [110]:
id(a)*id(b)

18069756836669055849209108736